sudo: required

language: nix

cache:
  directories:
    - ledger-master
    - ledger-next

os:
    - linux
    # - osx # Travis is saturated; see https://www.traviscistatus.com/

env:
  - EMACS_CI=emacs-24-3 LEDGER_BRANCH=master
  - EMACS_CI=emacs-24-4 LEDGER_BRANCH=master
  - EMACS_CI=emacs-24-5 LEDGER_BRANCH=master
  - EMACS_CI=emacs-25-1 LEDGER_BRANCH=master
  - EMACS_CI=emacs-25-2 LEDGER_BRANCH=master
  - EMACS_CI=emacs-25-3 LEDGER_BRANCH=master
  - EMACS_CI=emacs-26-1 LEDGER_BRANCH=master
  - EMACS_CI=emacs-26-2 LEDGER_BRANCH=master
  - EMACS_CI=emacs-26-3 LEDGER_BRANCH=master
  - EMACS_CI=emacs-snapshot LEDGER_BRANCH=next

matrix:
  allow_failures:
    - env: EMACS_CI=emacs-snapshot LEDGER_BRANCH=next

before_install:
  - ./tools/travis-install-ledger.sh $LEDGER_BRANCH
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        export PATH=$TRAVIS_BUILD_DIR/ledger-$LEDGER_BRANCH:$PATH;
    fi

install:
  - bash <(curl https://raw.githubusercontent.com/purcell/nix-emacs-ci/master/travis-install)

script:
  - emacs --version
  - ledger --version
  - emacs --eval "(setq byte-compile-error-on-warn (>= emacs-major-version 25))" -L .  --batch -f batch-byte-compile *.el
  - make -C test test-batch

after_script:
  - make -C test checkdoc

notifications:
  email: false
