sudo: required
language: generic
dist: xenial

env:
  matrix:
    - EVM_EMACS=emacs-24.3-travis
    - EVM_EMACS=emacs-25.1-travis
    # EVM doesn't support xenial yet, which we need since it has ledger version 3.
    # See https://github.com/rejeep/evm/issues/125
    # - EVM_EMACS=emacs-26.1-travis
    # - EVM_EMACS=emacs-26.2-travis
    # - EVM_EMACS=emacs-git-snapshot-travis

before_install:
  - sudo apt-get install -y ledger
  - git clone https://github.com/rejeep/evm.git $HOME/.evm
  - export PATH=$HOME/.evm/bin:$PATH
  - evm config path /tmp
  - evm install $EVM_EMACS --use --skip

script:
  - emacs --version
  - ledger --version
  - emacs --eval "(setq byte-compile-error-on-warn (>= emacs-major-version 25))" -L .  --batch -f batch-byte-compile *.el
  - make -C test test-batch

after_script:
  - make -C test checkdoc

notifications:
  email: false
